[functions]
  external_node_modules = ["express", "serverless-http", "@neondatabase/serverless", "bcryptjs", "body-parser", "cors", "dotenv", "jsonwebtoken"]
  included_files = ["server/routes/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true