[functions]
  directory = "netlify/functions"
  external_node_modules = ["express", "serverless-http", "@neondatabase/serverless", "bcryptjs"]

[build]
  base = "client"
  command = "vite build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true